# Generated by Django 2.1.3 on 2018-11-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='amount',
            new_name='milliliters',
        ),
        migrations.RemoveField(
            model_name='component',
            name='units',
        ),
        migrations.AlterField(
            model_name='liquid',
            name='type',
            field=models.CharField(choices=[('SHOTABLE', 'SHOTABLE'), ('MIXER', 'MIXER'), ('SYRUP', 'SYRUP')], max_length=32),
        ),
    ]
