# Generated by Django 2.1.3 on 2019-01-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixAPI', '0002_auto_20181128_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
